version: 2.1
jobs:
  build:
    docker:
      - image: fr3akyphantom/droid-builder:latest
    environment:
      MANIFEST_BRANCH: 'android-9.0'
      VERSION: '3.0.0'
      VENDOR: 'redmi'
      CODENAME: 'begonia'
      MAINTAINER: '@Flamefusion'
      BUILD_LUNCH: 'omni_begonia-eng'
      PB_OFFICIAL: 'true'
      CHANGELOG: |
        " - Initial Build"
    working_directory: /home/builder/pitchblack
    steps:
      - run:
          name: AIO Build
          command: |
            echo "Set GitAuth Infos too"
            git config --global user.email $GitHubMail
            git config --global user.name $GitHubName
            git config --global color.ui true
            wget -q https://raw.githubusercontent.com/PitchBlackRecoveryProject/vendor_utils/pb/build.sh
            source build.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: android-9.0
          context: org-global
